version: '3.6'
services:

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: 'no'
    logging:
      driver: journald
    user: telegraf
    env_file:
      - telegraf.env
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: 'no'
    logging:
      driver: journald
    environment:
      - INFLUXDB_DB=influx
    env_file:
      - influxdb.env
    volumes:
      - ./influxdb.conf:/etc/influxdb2/influxdb.conf
      - influxdb_data:/var/lib/influxdb2
    ports:
      - '8086:8086'

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: 'no'
    depends_on:
      - influxdb
    env_file:
      - grafana.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    profiles: 
      - interactive


volumes:
  grafana_data: {}
  influxdb_data: {}